-- Add lat/lng columns
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

-- Add state column for filtering
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS state TEXT;

-- Update existing businesses with state
UPDATE businesses SET state = 'AL' WHERE location LIKE '%AL%';

-- Insert 2 businesses per state (all paid/active)
INSERT INTO businesses (name, industry, address, location, state, website, bio, owner, contact, phone, status, payment_status, lat, lng) VALUES
-- Alaska
('Tundra Tiger Construction', 'Construction', '450 W Tudor Rd, Anchorage, AK 99503', 'Anchorage, AK', 'AK', 'https://tundratigerconstruction.com', 'Full-service general contractor specializing in cold-climate builds. Auburn engineering grad bringing Southern quality to the Last Frontier.', 'Ryan Mitchell', 'ryan@tundratigerconstruction.com', '(907) 555-0102', 'active', 'paid', 61.1901, -149.8197),
('Northern Lights Legal', 'Legal', '1029 W 3rd Ave, Anchorage, AK 99501', 'Anchorage, AK', 'AK', 'https://northernlightslegal.com', 'Estate planning and business law for Alaskan families. Auburn Law grad serving the frontier with trusted counsel.', 'Patricia Dunn', 'pat@northernlightslegal.com', '(907) 555-0234', 'active', 'paid', 61.2176, -149.8997),
-- Arizona
('Desert Eagle Dental', 'Healthcare', '7320 E Camelback Rd, Scottsdale, AZ 85251', 'Scottsdale, AZ', 'AZ', 'https://deserteagledental.com', 'Modern family dentistry in the heart of Scottsdale. Dr. Torres is an Auburn grad dedicated to comprehensive dental care in the desert.', 'Dr. Maria Torres', 'smile@deserteagledental.com', '(480) 555-0312', 'active', 'paid', 33.5092, -111.9280),
('Copper State Marketing', 'Marketing', '2525 E Arizona Biltmore Cir, Phoenix, AZ 85016', 'Phoenix, AZ', 'AZ', 'https://copperstatemarketing.com', 'Digital marketing agency helping Arizona businesses grow. Auburn Harbert College alum bringing SEC-level strategy to the Southwest.', 'Jake Simmons', 'jake@copperstatemarketing.com', '(602) 555-0198', 'active', 'paid', 33.5186, -112.0161),
-- Arkansas
('Razorback Rival BBQ', 'Food & Beverage', '1000 Main St, Little Rock, AR 72202', 'Little Rock, AR', 'AR', 'https://razorbackrivalbbq.com', 'Smoked meats with an Auburn attitude right in Razorback country. War Eagle in every bite. Best brisket in Little Rock.', 'Damon Wells', 'eat@razorbackrivalbbq.com', '(501) 555-0187', 'active', 'paid', 34.7465, -92.2896),
('Natural State Insurance', 'Insurance', '415 N McKinley St, Little Rock, AR 72205', 'Little Rock, AR', 'AR', 'https://naturalstateinsurance.com', 'Independent insurance for Arkansas families. Auburn grad offering home, auto, and business coverage with Auburn values.', 'Carla Bennett', 'carla@naturalstateinsurance.com', '(501) 555-0299', 'active', 'paid', 34.7544, -92.3102),
-- California
('Golden Tiger Tech', 'Technology', '600 B St, San Diego, CA 92101', 'San Diego, CA', 'CA', 'https://goldentigertechsd.com', 'IT consulting and cloud solutions for California businesses. Auburn CS grads building reliable tech on the West Coast.', 'Marcus Kim', 'info@goldentigertechsd.com', '(619) 555-0422', 'active', 'paid', 32.7157, -117.1611),
('Pacific Plains Realty', 'Real Estate', '9601 Wilshire Blvd, Beverly Hills, CA 90210', 'Los Angeles, CA', 'CA', 'https://pacificplainsrealty.com', 'Luxury real estate for Auburn families relocating to Southern California. We know the Plains and the Pacific.', 'Whitney Ross', 'homes@pacificplainsrealty.com', '(310) 555-0533', 'active', 'paid', 34.0696, -118.3990),
-- Colorado
('Mile High Tiger Fitness', 'Health & Fitness', '1600 Champa St, Denver, CO 80202', 'Denver, CO', 'CO', 'https://milehightigerfitness.com', 'Boutique gym and personal training in downtown Denver. Built by Auburn athletes who believe in pushing limits at altitude.', 'Derek Larson', 'train@milehightigerfitness.com', '(303) 555-0644', 'active', 'paid', 39.7456, -104.9890),
('Front Range Financial', 'Financial Services', '1515 Arapahoe St, Denver, CO 80202', 'Denver, CO', 'CO', 'https://frontrangefinancial.com', 'Wealth management for Colorado professionals. Auburn MBA helping families build long-term financial plans.', 'Angela Price', 'angela@frontrangefinancial.com', '(303) 555-0755', 'active', 'paid', 39.7489, -104.9983),
-- Connecticut
('Charter Oak Accounting', 'Financial Services', '265 Church St, New Haven, CT 06510', 'New Haven, CT', 'CT', 'https://charteroakaccounting.com', 'CPA firm serving Connecticut small businesses. Auburn accounting alum with a passion for helping entrepreneurs thrive.', 'Steven Crane', 'steve@charteroakaccounting.com', '(203) 555-0811', 'active', 'paid', 41.3083, -72.9279),
('Nutmeg Tiger Landscaping', 'Home Services', '150 Trumbull St, Hartford, CT 06103', 'Hartford, CT', 'CT', 'https://nutmegtigerlandscaping.com', 'Professional landscaping for Connecticut homes. Auburn horticulture grad creating beautiful outdoor spaces in New England.', 'Brian Foster', 'brian@nutmegtigerlandscaping.com', '(860) 555-0922', 'active', 'paid', 41.7658, -72.6734),
-- Delaware
('First State Legal Group', 'Legal', '1000 N West St, Wilmington, DE 19801', 'Wilmington, DE', 'DE', 'https://firststatelegalgroup.com', 'Corporate law and business formation in Delaware. Auburn Law alumni helping businesses incorporate in the First State.', 'Robert Chen', 'rob@firststatelegalgroup.com', '(302) 555-0133', 'active', 'paid', 39.7447, -75.5484),
('Blue Hen Tiger Auto', 'Automotive', '301 E Main St, Newark, DE 19711', 'Newark, DE', 'DE', 'https://bluehentigerauto.com', 'Honest auto repair in Newark. Auburn mechanical engineering grad who treats every car like his own.', 'Tommy Richards', 'tommy@bluehentigerauto.com', '(302) 555-0244', 'active', 'paid', 39.6837, -75.7497),
-- Florida
('Sunshine Tiger Dental', 'Healthcare', '401 E Jackson St, Tampa, FL 33602', 'Tampa, FL', 'FL', 'https://sunshinetigerdental.com', 'Family dentistry for Tampa Bay. Auburn grad providing gentle care and big smiles in the Sunshine State.', 'Dr. Lisa Morgan', 'smile@sunshinetigerdental.com', '(813) 555-0355', 'active', 'paid', 27.9472, -82.4584),
('Gulf Coast Tiger Realty', 'Real Estate', '100 S Eola Dr, Orlando, FL 32801', 'Orlando, FL', 'FL', 'https://gulfcoasttigerrealty.com', 'Helping Auburn families find homes in Central Florida. From the Plains to the palms.', 'Jennifer Walsh', 'jen@gulfcoasttigerrealty.com', '(407) 555-0466', 'active', 'paid', 28.5383, -81.3792),
-- Georgia
('Peach State Tiger Construction', 'Construction', '191 Peachtree St NE, Atlanta, GA 30303', 'Atlanta, GA', 'GA', 'https://peachstatetigerconstruction.com', 'Commercial and residential builds in Metro Atlanta. Auburn building science grad bringing quality to every project.', 'Marcus Johnson', 'marcus@peachstatetigerconstruction.com', '(404) 555-0577', 'active', 'paid', 33.7590, -84.3880),
('Atlanta Eagle Brewing', 'Food & Beverage', '550 Somerset Terrace NE, Atlanta, GA 30306', 'Atlanta, GA', 'GA', 'https://atlantaeaglebrewing.com', 'Craft beer with Auburn soul in the heart of Atlanta. Our taproom is the best Auburn watch party spot in Georgia.', 'Chris Sullivan', 'cheers@atlantaeaglebrewing.com', '(404) 555-0688', 'active', 'paid', 33.7824, -84.3495),
-- Hawaii
('Aloha Tiger Fitness', 'Health & Fitness', '1450 Ala Moana Blvd, Honolulu, HI 96814', 'Honolulu, HI', 'HI', 'https://alohatigerfitness.com', 'Personal training and yoga in paradise. Auburn kinesiology grad helping island residents live their healthiest lives.', 'Kai Nakamura', 'kai@alohatigerfitness.com', '(808) 555-0799', 'active', 'paid', 21.2891, -157.8416),
('Island Eagle Photography', 'Creative Services', '2301 Kalakaua Ave, Honolulu, HI 96815', 'Honolulu, HI', 'HI', 'https://islandeaglephotography.com', 'Wedding and event photography in Hawaii. Auburn visual arts grad capturing your most beautiful moments.', 'Amanda Keahi', 'book@islandeaglephotography.com', '(808) 555-0811', 'active', 'paid', 21.2770, -157.8263),
-- Idaho
('Gem State Tiger Plumbing', 'Home Services', '802 W Bannock St, Boise, ID 83702', 'Boise, ID', 'ID', 'https://gemstatetigerplumbing.com', 'Licensed plumber serving the Treasure Valley. Auburn grad with 10 years of honest, reliable service.', 'Dale Patterson', 'dale@gemstatetigerplumbing.com', '(208) 555-0922', 'active', 'paid', 43.6150, -116.2023),
('Boise Eagle Insurance', 'Insurance', '250 S 5th St, Boise, ID 83702', 'Boise, ID', 'ID', 'https://boiseeagleinsurance.com', 'Independent insurance agency in Boise. Auburn business grad protecting Idaho families and businesses.', 'Sarah Fleming', 'sarah@boiseeagleinsurance.com', '(208) 555-0133', 'active', 'paid', 43.6177, -116.2025),
-- Illinois
('Windy City Tiger Law', 'Legal', '311 S Wacker Dr, Chicago, IL 60606', 'Chicago, IL', 'IL', 'https://windycitytigerlaw.com', 'Business litigation and corporate law in downtown Chicago. Auburn Law grad fighting for your interests.', 'David Park', 'david@windycitytigerlaw.com', '(312) 555-0244', 'active', 'paid', 41.8768, -87.6359),
('Prairie Eagle Marketing', 'Marketing', '222 Merchandise Mart Plz, Chicago, IL 60654', 'Chicago, IL', 'IL', 'https://prairieeaglemarketing.com', 'Full-service digital agency in Chicago. Auburn communications grads helping Midwest brands grow.', 'Kelly Wright', 'kelly@prairieeaglemarketing.com', '(312) 555-0355', 'active', 'paid', 41.8885, -87.6354),
-- Indiana
('Hoosier Tiger Electric', 'Home Services', '40 W Washington St, Indianapolis, IN 46204', 'Indianapolis, IN', 'IN', 'https://hoosiertigerelectric.com', 'Licensed electrician serving Indianapolis. Auburn building construction grad wiring Indy homes and businesses.', 'Tom Bradley', 'tom@hoosiertigerelectric.com', '(317) 555-0466', 'active', 'paid', 39.7684, -86.1581),
('Circle City Eagle Coffee', 'Food & Beverage', '120 E Market St, Indianapolis, IN 46204', 'Indianapolis, IN', 'IN', 'https://circlecityeaglecoffee.com', 'Specialty coffee roasted in Indianapolis. Auburn family serving War Eagle vibes in the heartland.', 'Nina Patel', 'hello@circlecityeaglecoffee.com', '(317) 555-0577', 'active', 'paid', 39.7683, -86.1543),
-- Iowa
('Hawkeye Tiger Accounting', 'Financial Services', '666 Walnut St, Des Moines, IA 50309', 'Des Moines, IA', 'IA', 'https://hawkeyetigeraccounting.com', 'Tax prep and bookkeeping in Des Moines. Auburn accounting grad helping Iowa families and small businesses.', 'Greg Olson', 'greg@hawkeyetigeraccounting.com', '(515) 555-0688', 'active', 'paid', 41.5868, -93.6250),
('Tall Corn Tiger Realty', 'Real Estate', '400 Locust St, Des Moines, IA 50309', 'Des Moines, IA', 'IA', 'https://tallcorntigerrealty.com', 'Residential real estate in Central Iowa. Auburn alum helping families find their Iowa home.', 'Michelle Hart', 'michelle@tallcorntigerrealty.com', '(515) 555-0799', 'active', 'paid', 41.5862, -93.6241),
-- Kansas
('Sunflower Tiger Auto', 'Automotive', '535 S Kansas Ave, Topeka, KS 66603', 'Topeka, KS', 'KS', 'https://sunflowertigerauto.com', 'Auto repair and maintenance in Topeka. Auburn grad providing honest service to Kansas families.', 'Pete Garrison', 'pete@sunflowertigerauto.com', '(785) 555-0811', 'active', 'paid', 39.0558, -95.6764),
('Wheat State Eagle Tech', 'Technology', '100 N Broadway, Wichita, KS 67202', 'Wichita, KS', 'KS', 'https://wheatstateeagletech.com', 'Managed IT services for Kansas businesses. Auburn CS grad keeping your systems running reliably.', 'Amy Nguyen', 'amy@wheatstateeagletech.com', '(316) 555-0922', 'active', 'paid', 37.6872, -97.3301),
-- Kentucky
('Bluegrass Tiger BBQ', 'Food & Beverage', '401 W Main St, Louisville, KY 40202', 'Louisville, KY', 'KY', 'https://bluegrasstigerbbq.com', 'Southern BBQ with Auburn pride in bourbon country. Smoked low and slow, served with War Eagle spirit.', 'DeShawn Carter', 'eat@bluegrasstigerbbq.com', '(502) 555-0133', 'active', 'paid', 38.2576, -85.7584),
('Derby Eagle Dental', 'Healthcare', '250 E Liberty St, Louisville, KY 40202', 'Louisville, KY', 'KY', 'https://derbyeagledental.com', 'Cosmetic and family dentistry in Louisville. Auburn dental grad creating confident smiles in the Bluegrass.', 'Dr. Priya Shah', 'smile@derbyeagledental.com', '(502) 555-0244', 'active', 'paid', 38.2541, -85.7520),
-- Louisiana
('Bayou Tiger Legal', 'Legal', '201 St Charles Ave, New Orleans, LA 70170', 'New Orleans, LA', 'LA', 'https://bayoutigerlegal.com', 'Personal injury and business law in NOLA. Auburn Law grad fighting for Louisiana families.', 'Andre Duplantis', 'andre@bayoutigerlegal.com', '(504) 555-0355', 'active', 'paid', 29.9490, -90.0701),
('Crescent Eagle Catering', 'Food & Beverage', '800 Magazine St, New Orleans, LA 70130', 'New Orleans, LA', 'LA', 'https://crescenteaglecatering.com', 'Event catering with Southern flair. Auburn hospitality grad bringing Auburn charm to NOLA celebrations.', 'Monique James', 'events@crescenteaglecatering.com', '(504) 555-0466', 'active', 'paid', 29.9430, -90.0713),
-- Maine
('Pine Tree Tiger Construction', 'Construction', '100 Middle St, Portland, ME 04101', 'Portland, ME', 'ME', 'https://pinetreetigerconstruction.com', 'Custom home building in coastal Maine. Auburn building science grad crafting New England homes with Southern quality.', 'Ethan Brooks', 'ethan@pinetreetigerconstruction.com', '(207) 555-0577', 'active', 'paid', 43.6591, -70.2568),
('Lighthouse Eagle Financial', 'Financial Services', '2 Monument Sq, Portland, ME 04101', 'Portland, ME', 'ME', 'https://lighthouseeaglefinancial.com', 'Financial planning for Maine families. Auburn finance grad helping you navigate your financial future.', 'Catherine Wells', 'catherine@lighthouseeaglefinancial.com', '(207) 555-0688', 'active', 'paid', 43.6600, -70.2571),
-- Maryland
('Chesapeake Tiger IT', 'Technology', '100 E Pratt St, Baltimore, MD 21202', 'Baltimore, MD', 'MD', 'https://chesapeaketigerit.com', 'Cybersecurity and IT consulting in Baltimore. Auburn CS grad protecting Maryland businesses from digital threats.', 'James Okafor', 'james@chesapeaketigerit.com', '(410) 555-0799', 'active', 'paid', 39.2868, -76.6122),
('Old Line Eagle Realty', 'Real Estate', '7 E Redwood St, Baltimore, MD 21202', 'Baltimore, MD', 'MD', 'https://oldlineeaglerealty.com', 'Residential real estate in the DMV area. Auburn alum helping families find their Maryland home.', 'Diana Powell', 'diana@oldlineeaglerealty.com', '(410) 555-0811', 'active', 'paid', 39.2889, -76.6148),
-- Massachusetts
('Bay State Tiger Law', 'Legal', '1 Beacon St, Boston, MA 02108', 'Boston, MA', 'MA', 'https://baystatetigerlaw.com', 'Corporate and IP law in downtown Boston. Auburn Law grad serving New England businesses.', 'Richard Lane', 'richard@baystatetigerlaw.com', '(617) 555-0922', 'active', 'paid', 42.3588, -71.0637),
('Patriots Eagle Fitness', 'Health & Fitness', '200 Newbury St, Boston, MA 02116', 'Boston, MA', 'MA', 'https://patriotseaglefitness.com', 'Personal training and group classes in Back Bay. Auburn kinesiology grad getting Boston fit.', 'Tara Simmons', 'tara@patriotseaglefitness.com', '(617) 555-0133', 'active', 'paid', 42.3501, -71.0777),
-- Michigan
('Great Lakes Tiger Brewing', 'Food & Beverage', '600 Woodward Ave, Detroit, MI 48226', 'Detroit, MI', 'MI', 'https://greatlakestigerbrewing.com', 'Craft beer in the Motor City. Auburn grads brewing with Southern tradition and Midwest grit.', 'Kyle Anderson', 'cheers@greatlakestigerbrewing.com', '(313) 555-0244', 'active', 'paid', 42.3314, -83.0458),
('Wolverine Eagle Electric', 'Home Services', '1301 3rd St, Detroit, MI 48226', 'Detroit, MI', 'MI', 'https://wolverineeagleelectric.com', 'Commercial and residential electrical in Metro Detroit. Auburn grad lighting up Michigan.', 'Paul Kowalski', 'paul@wolverineeagleelectric.com', '(313) 555-0355', 'active', 'paid', 42.3361, -83.0509),
-- Minnesota
('North Star Tiger Dental', 'Healthcare', '50 S 6th St, Minneapolis, MN 55402', 'Minneapolis, MN', 'MN', 'https://northstartigerdental.com', 'Modern dentistry in downtown Minneapolis. Auburn dental grad providing top-tier care in the Twin Cities.', 'Dr. Sarah Lindgren', 'smile@northstartigerdental.com', '(612) 555-0466', 'active', 'paid', 44.9778, -93.2692),
('Twin Cities Eagle Marketing', 'Marketing', '700 Nicollet Mall, Minneapolis, MN 55402', 'Minneapolis, MN', 'MN', 'https://twincitieseaglemarketing.com', 'Brand strategy and digital marketing for Minnesota businesses. Auburn comm grads growing Northern brands.', 'Rachel Kim', 'rachel@twincitieseaglemarketing.com', '(612) 555-0577', 'active', 'paid', 44.9764, -93.2710),
-- Mississippi
('Magnolia Tiger Law', 'Legal', '200 S Lamar Blvd, Jackson, MS 39201', 'Jackson, MS', 'MS', 'https://magnoliatigerlegal.com', 'Family and estate law in Jackson. Auburn Law grad serving Mississippi families with integrity.', 'William Grant', 'william@magnoliatigerlegal.com', '(601) 555-0688', 'active', 'paid', 32.2988, -90.1848),
('Delta Eagle Insurance', 'Insurance', '401 E Capitol St, Jackson, MS 39201', 'Jackson, MS', 'MS', 'https://deltaeagleinsurance.com', 'Home, auto, and business insurance for Mississippi. Auburn grad protecting Delta families.', 'Patricia Moon', 'pat@deltaeagleinsurance.com', '(601) 555-0799', 'active', 'paid', 32.2998, -90.1818),
-- Missouri
('Gateway Tiger Realty', 'Real Estate', '100 N Broadway, St. Louis, MO 63102', 'St. Louis, MO', 'MO', 'https://gatewaytigerrealty.com', 'Helping Auburn families find homes in the Gateway City. From the Plains to the Arch.', 'Kevin Murphy', 'kevin@gatewaytigerrealty.com', '(314) 555-0811', 'active', 'paid', 38.6270, -90.1994),
('Show Me Eagle Coffee', 'Food & Beverage', '700 Market St, St. Louis, MO 63101', 'St. Louis, MO', 'MO', 'https://showmeeaglecoffee.com', 'Specialty coffee in downtown St. Louis. Auburn family roasting beans with War Eagle pride.', 'Jasmine Taylor', 'hello@showmeeaglecoffee.com', '(314) 555-0922', 'active', 'paid', 38.6281, -90.1938),
-- Montana
('Big Sky Tiger Construction', 'Construction', '27 N Last Chance Gulch, Helena, MT 59601', 'Helena, MT', 'MT', 'https://bigskytigerconstruction.com', 'Custom builds in Big Sky country. Auburn building science grad crafting Montana homes.', 'Luke Henderson', 'luke@bigskytigerconstruction.com', '(406) 555-0133', 'active', 'paid', 46.5884, -112.0391),
('Treasure State Eagle Vet', 'Healthcare', '3040 N Montana Ave, Helena, MT 59602', 'Helena, MT', 'MT', 'https://treasurestateeaglevet.com', 'Veterinary care for Montana pets and livestock. Auburn vet school grad caring for Big Sky animals.', 'Dr. Megan O''Brien', 'care@treasurestateeaglevet.com', '(406) 555-0244', 'active', 'paid', 46.6091, -112.0365),
-- Nebraska
('Cornhusker Tiger Auto', 'Automotive', '1001 Farnam St, Omaha, NE 68102', 'Omaha, NE', 'NE', 'https://cornhuskertigerauto.com', 'Full-service auto repair in Omaha. Auburn mechanical engineering grad keeping Nebraska on the road.', 'Scott Phillips', 'scott@cornhuskertigerauto.com', '(402) 555-0355', 'active', 'paid', 41.2565, -95.9345),
('Prairie Eagle Financial', 'Financial Services', '1400 Douglas St, Omaha, NE 68102', 'Omaha, NE', 'NE', 'https://prairieeaglefinancial.com', 'Wealth advisory in the heartland. Auburn finance grad managing portfolios for Nebraska families.', 'Laura Chen', 'laura@prairieeaglefinancial.com', '(402) 555-0466', 'active', 'paid', 41.2587, -95.9372),
-- Nevada
('Silver State Tiger Tech', 'Technology', '300 S 4th St, Las Vegas, NV 89101', 'Las Vegas, NV', 'NV', 'https://silverstatetigertech.com', 'IT solutions for Vegas businesses. Auburn CS grad building reliable systems in the desert.', 'Alex Moreno', 'alex@silverstatetigertech.com', '(702) 555-0577', 'active', 'paid', 36.1699, -115.1398),
('Neon Eagle Marketing', 'Marketing', '3900 Paradise Rd, Las Vegas, NV 89169', 'Las Vegas, NV', 'NV', 'https://neoneaglemarketing.com', 'Digital marketing and branding for Nevada businesses. Auburn grads making brands shine in Vegas.', 'Brittany Cole', 'brittany@neoneaglemarketing.com', '(702) 555-0688', 'active', 'paid', 36.1215, -115.1539),
-- New Hampshire
('Granite Tiger Plumbing', 'Home Services', '20 Central Sq, Keene, NH 03431', 'Keene, NH', 'NH', 'https://granitetigerplumbing.com', 'Licensed plumbing in southern New Hampshire. Auburn grad with reliable, honest service.', 'Dan McCarthy', 'dan@granitetigerplumbing.com', '(603) 555-0799', 'active', 'paid', 42.9339, -72.2789),
('White Mountain Eagle Realty', 'Real Estate', '815 Elm St, Manchester, NH 03101', 'Manchester, NH', 'NH', 'https://whitemountaineaglerealty.com', 'Residential real estate in New Hampshire. Auburn alum helping families find their New England home.', 'Elizabeth Fox', 'liz@whitemountaineaglerealty.com', '(603) 555-0811', 'active', 'paid', 42.9870, -71.4641),
-- New Jersey
('Garden State Tiger Law', 'Legal', '744 Broad St, Newark, NJ 07102', 'Newark, NJ', 'NJ', 'https://gardenstatetigerlaw.com', 'Business and immigration law in Northern Jersey. Auburn Law grad serving the tri-state area.', 'David Gutierrez', 'david@gardenstatetigerlaw.com', '(973) 555-0922', 'active', 'paid', 40.7357, -74.1724),
('Shore Eagle Dental', 'Healthcare', '240 Old Bridge Turnpike, South River, NJ 08882', 'South River, NJ', 'NJ', 'https://shoreeagledental.com', 'Family dentistry near the Jersey Shore. Auburn dental grad with a gentle touch.', 'Dr. Amy Chen', 'smile@shoreeagledental.com', '(732) 555-0133', 'active', 'paid', 40.4486, -74.3718),
-- New Mexico
('Enchanted Tiger Realty', 'Real Estate', '200 3rd St NW, Albuquerque, NM 87102', 'Albuquerque, NM', 'NM', 'https://enchantedtigerrealty.com', 'Helping Auburn families find homes in the Land of Enchantment. Desert living with Auburn values.', 'Maria Santos', 'maria@enchantedtigerrealty.com', '(505) 555-0244', 'active', 'paid', 35.0844, -106.6504),
('Rio Grande Eagle Auto', 'Automotive', '500 Central Ave NW, Albuquerque, NM 87102', 'Albuquerque, NM', 'NM', 'https://riograndeeagleauto.com', 'Reliable auto repair in Albuquerque. Auburn-trained mechanic serving New Mexico drivers.', 'Carlos Vigil', 'carlos@riograndeeagleauto.com', '(505) 555-0355', 'active', 'paid', 35.0853, -106.6564),
-- New York
('Empire Tiger Consulting', 'Technology', '350 5th Ave, New York, NY 10118', 'New York, NY', 'NY', 'https://empiretigerconsulting.com', 'Tech consulting in Midtown Manhattan. Auburn engineers solving complex problems for NYC enterprises.', 'Jonathan Lee', 'jon@empiretigerconsulting.com', '(212) 555-0466', 'active', 'paid', 40.7484, -73.9857),
('Brooklyn Eagle Coffee', 'Food & Beverage', '300 Smith St, Brooklyn, NY 11231', 'Brooklyn, NY', 'NY', 'https://brooklyneaglecoffee.com', 'Specialty coffee in Carroll Gardens. Auburn family roasting with love in the city that never sleeps.', 'Maya Richardson', 'hello@brooklyneaglecoffee.com', '(718) 555-0577', 'active', 'paid', 40.6826, -73.9934),
-- North Carolina
('Tar Heel Tiger Construction', 'Construction', '301 Fayetteville St, Raleigh, NC 27601', 'Raleigh, NC', 'NC', 'https://tarheeltigerconstruction.com', 'Custom home building in the Triangle. Auburn building science grad with a reputation for quality.', 'Marcus Williams', 'marcus@tarheeltigerconstruction.com', '(919) 555-0688', 'active', 'paid', 35.7796, -78.6382),
('Queen City Eagle Brewing', 'Food & Beverage', '100 N Tryon St, Charlotte, NC 28202', 'Charlotte, NC', 'NC', 'https://queencityeaglebrewing.com', 'Craft beer in Uptown Charlotte. Auburn grads pouring War Eagle pride in every pint.', 'Derek Mason', 'cheers@queencityeaglebrewing.com', '(704) 555-0799', 'active', 'paid', 35.2271, -80.8431),
-- North Dakota
('Prairie Tiger Plumbing', 'Home Services', '400 E Broadway Ave, Bismarck, ND 58501', 'Bismarck, ND', 'ND', 'https://prairietigerplumbing.com', 'Licensed plumbing for North Dakota homes. Auburn grad bringing reliable service to the Northern Plains.', 'Mike Jensen', 'mike@prairietigerplumbing.com', '(701) 555-0811', 'active', 'paid', 46.8083, -100.7837),
('Peace Garden Eagle Insurance', 'Insurance', '200 N 3rd St, Bismarck, ND 58501', 'Bismarck, ND', 'ND', 'https://peacegardeneagleinsurance.com', 'Comprehensive insurance for North Dakota families. Auburn business grad protecting your assets.', 'Heather Olson', 'heather@peacegardeneagleinsurance.com', '(701) 555-0922', 'active', 'paid', 46.8083, -100.7839),
-- Ohio
('Buckeye Tiger Legal', 'Legal', '200 Public Sq, Cleveland, OH 44114', 'Cleveland, OH', 'OH', 'https://buckeyetigerlegal.com', 'Business law and litigation in Cleveland. Auburn Law grad serving Northeast Ohio with integrity.', 'Daniel Harris', 'daniel@buckeyetigerlegal.com', '(216) 555-0133', 'active', 'paid', 41.4993, -81.6944),
('Heartland Eagle Dental', 'Healthcare', '1 E Broad St, Columbus, OH 43215', 'Columbus, OH', 'OH', 'https://heartlandeagledental.com', 'Modern family dentistry in Columbus. Auburn grad providing compassionate care in the Buckeye State.', 'Dr. Rebecca Foster', 'smile@heartlandeagledental.com', '(614) 555-0244', 'active', 'paid', 39.9612, -82.9988),
-- Oklahoma
('Sooner Tiger Auto', 'Automotive', '210 Park Ave, Oklahoma City, OK 73102', 'Oklahoma City, OK', 'OK', 'https://soonertigerauto.com', 'Full-service auto repair in OKC. Auburn-trained mechanic bringing quality to the Sooner State.', 'Travis Long', 'travis@soonertigerauto.com', '(405) 555-0355', 'active', 'paid', 35.4676, -97.5164),
('Tornado Eagle Tech', 'Technology', '100 W 5th St, Tulsa, OK 74103', 'Tulsa, OK', 'OK', 'https://tornadoeagletech.com', 'IT solutions for Oklahoma businesses. Auburn CS grad keeping your tech running in tornado alley.', 'Priya Patel', 'priya@tornadoeagletech.com', '(918) 555-0466', 'active', 'paid', 36.1540, -95.9928),
-- Oregon
('Beaver Tiger Brewing', 'Food & Beverage', '1337 NW Flanders St, Portland, OR 97209', 'Portland, OR', 'OR', 'https://beavertigerbrewing.com', 'Craft beer in Portland. Auburn family brewing with Southern roots and Pacific Northwest hops.', 'Ryan Peters', 'cheers@beavertigerbrewing.com', '(503) 555-0577', 'active', 'paid', 45.5266, -122.6849),
('Rose City Eagle Realty', 'Real Estate', '921 SW Washington St, Portland, OR 97205', 'Portland, OR', 'OR', 'https://rosecityeaglerealty.com', 'Helping Auburn families find homes in the Pacific Northwest. From the Plains to the pines.', 'Megan Clark', 'megan@rosecityeaglerealty.com', '(503) 555-0688', 'active', 'paid', 45.5202, -122.6787),
-- Pennsylvania
('Keystone Tiger Law', 'Legal', '1500 Market St, Philadelphia, PA 19102', 'Philadelphia, PA', 'PA', 'https://keystonetigerlaw.com', 'Corporate and IP law in Philly. Auburn Law grad serving the Greater Philadelphia business community.', 'Michael DiAngelo', 'mike@keystonetigerlaw.com', '(215) 555-0799', 'active', 'paid', 39.9526, -75.1652),
('Steel City Eagle Fitness', 'Health & Fitness', '525 William Penn Pl, Pittsburgh, PA 15219', 'Pittsburgh, PA', 'PA', 'https://steelcityeaglefitness.com', 'Boutique gym in downtown Pittsburgh. Auburn athletics grad training the Steel City to be their best.', 'Nicole Powers', 'train@steelcityeaglefitness.com', '(412) 555-0811', 'active', 'paid', 40.4406, -79.9959),
-- Rhode Island
('Ocean State Tiger Landscaping', 'Home Services', '1 Dorrance St, Providence, RI 02903', 'Providence, RI', 'RI', 'https://oceanstatetigerlandscaping.com', 'Professional landscaping in Rhode Island. Auburn horticulture grad creating beautiful New England gardens.', 'Ben Moretti', 'ben@oceanstatetigerlandscaping.com', '(401) 555-0922', 'active', 'paid', 41.8240, -71.4128),
('Narragansett Eagle Café', 'Food & Beverage', '225 Dyer St, Providence, RI 02903', 'Providence, RI', 'RI', 'https://narragansetteaglecafe.com', 'Farm-to-table café with Auburn heart. Southern hospitality meets New England charm.', 'Olivia Grant', 'hello@narragansetteaglecafe.com', '(401) 555-0133', 'active', 'paid', 41.8197, -71.4077),
-- South Carolina
('Palmetto Tiger Realty', 'Real Estate', '22 N Main St, Greenville, SC 29601', 'Greenville, SC', 'SC', 'https://palmettotigerrealty.com', 'Upstate SC real estate for Auburn families. Just a short drive from the Plains and we know it well.', 'Ashley Brooks', 'ashley@palmettotigerrealty.com', '(864) 555-0244', 'active', 'paid', 34.8526, -82.3940),
('Holy City Eagle Catering', 'Food & Beverage', '100 Market St, Charleston, SC 29401', 'Charleston, SC', 'SC', 'https://holycityeaglecatering.com', 'Lowcountry catering with Auburn pride. Perfect for weddings, corporate events, and gameday parties.', 'Danielle Thompson', 'events@holycityeaglecatering.com', '(843) 555-0355', 'active', 'paid', 32.7765, -79.9311),
-- South Dakota
('Mount Rushmore Tiger Insurance', 'Insurance', '600 Main St, Rapid City, SD 57701', 'Rapid City, SD', 'SD', 'https://mtrushmoretigerinsurance.com', 'Independent insurance in the Black Hills. Auburn business grad protecting South Dakota families.', 'Brian Schultz', 'brian@mtrushmoretigerinsurance.com', '(605) 555-0466', 'active', 'paid', 44.0805, -103.2310),
('Coyote Eagle Financial', 'Financial Services', '101 S Main Ave, Sioux Falls, SD 57104', 'Sioux Falls, SD', 'SD', 'https://coyoteeaglefinancial.com', 'Financial planning in Sioux Falls. Auburn finance grad building wealth for Dakota families.', 'Janet Peterson', 'janet@coyoteeaglefinancial.com', '(605) 555-0577', 'active', 'paid', 43.5460, -96.7313),
-- Tennessee
('Volunteer Tiger BBQ', 'Food & Beverage', '150 4th Ave N, Nashville, TN 37219', 'Nashville, TN', 'TN', 'https://volunteertigerbbq.com', 'Auburn-style BBQ in Music City. Smoked meats and Southern sides in the heart of Nashville.', 'Terrence Davis', 'eat@volunteertigerbbq.com', '(615) 555-0688', 'active', 'paid', 36.1627, -86.7816),
('Memphis Eagle Law', 'Legal', '80 Monroe Ave, Memphis, TN 38103', 'Memphis, TN', 'TN', 'https://memphiseaglelaw.com', 'Personal injury and business law in Memphis. Auburn Law grad fighting for Tennessee families.', 'Crystal Robinson', 'crystal@memphiseaglelaw.com', '(901) 555-0799', 'active', 'paid', 35.1455, -90.0513),
-- Texas
('Lone Star Tiger Realty', 'Real Estate', '500 Main St, Houston, TX 77002', 'Houston, TX', 'TX', 'https://lonestartigerrealty.com', 'Houston real estate for Auburn families. Helping you find your Texas home with Auburn values.', 'Brandon Scott', 'brandon@lonestartigerrealty.com', '(713) 555-0811', 'active', 'paid', 29.7604, -95.3698),
('Big Tex Eagle BBQ', 'Food & Beverage', '2300 Commerce St, Dallas, TX 75201', 'Dallas, TX', 'TX', 'https://bigtexeaglebbq.com', 'Texas BBQ with Auburn heart. Best brisket in Dallas, served with War Eagle spirit.', 'James Washington', 'eat@bigtexeaglebbq.com', '(214) 555-0922', 'active', 'paid', 32.7825, -96.7968),
-- Utah
('Beehive Tiger Tech', 'Technology', '222 S Main St, Salt Lake City, UT 84101', 'Salt Lake City, UT', 'UT', 'https://beehivetigertech.com', 'Software development in SLC. Auburn CS grad building apps and websites for Utah businesses.', 'Nathan Park', 'nathan@beehivetigertech.com', '(801) 555-0133', 'active', 'paid', 40.7608, -111.8910),
('Zion Eagle Fitness', 'Health & Fitness', '15 E 100 South, Salt Lake City, UT 84111', 'Salt Lake City, UT', 'UT', 'https://zioneaglefitness.com', 'Boutique gym and personal training in Salt Lake. Auburn kinesiology grad helping Utah stay fit.', 'Taylor Briggs', 'train@zioneaglefitness.com', '(801) 555-0244', 'active', 'paid', 40.7649, -111.8880),
-- Vermont
('Green Mountain Tiger Café', 'Food & Beverage', '134 Church St, Burlington, VT 05401', 'Burlington, VT', 'VT', 'https://greenmountaintigercafe.com', 'Farm-to-table café in Burlington. Auburn hospitality grad serving local Vermont flavors with Southern charm.', 'Emma Russo', 'hello@greenmountaintigercafe.com', '(802) 555-0355', 'active', 'paid', 44.4759, -73.2121),
('Maple Eagle Insurance', 'Insurance', '89 Main St, Burlington, VT 05401', 'Burlington, VT', 'VT', 'https://mapleeagleinsurance.com', 'Home and business insurance for Vermont families. Auburn grad protecting your piece of New England.', 'Tom Everett', 'tom@mapleeagleinsurance.com', '(802) 555-0466', 'active', 'paid', 44.4761, -73.2124),
-- Virginia
('Old Dominion Tiger Law', 'Legal', '700 E Main St, Richmond, VA 23219', 'Richmond, VA', 'VA', 'https://olddominiontigerlaw.com', 'Business and estate law in Virginia''s capital. Auburn Law grad serving the Commonwealth.', 'Patricia Davis', 'pat@olddominiontigerlaw.com', '(804) 555-0577', 'active', 'paid', 37.5407, -77.4360),
('Shenandoah Eagle Realty', 'Real Estate', '1001 E Broad St, Richmond, VA 23219', 'Richmond, VA', 'VA', 'https://shenandoaheaglerealty.com', 'Virginia real estate for Auburn families. From the Valley to the Bay, we know Virginia.', 'Michael Thompson', 'michael@shenandoaheaglerealty.com', '(804) 555-0688', 'active', 'paid', 37.5420, -77.4300),
-- Washington
('Evergreen Tiger Tech', 'Technology', '400 Broad St, Seattle, WA 98109', 'Seattle, WA', 'WA', 'https://evergreentigertechseattle.com', 'Cloud and DevOps consulting in Seattle. Auburn engineers solving big tech problems in the Pacific Northwest.', 'Jason Kim', 'jason@evergreentigertechseattle.com', '(206) 555-0799', 'active', 'paid', 47.6205, -122.3493),
('Puget Sound Eagle Coffee', 'Food & Beverage', '1912 Pike Pl, Seattle, WA 98101', 'Seattle, WA', 'WA', 'https://pugetsoundeaglecoffee.com', 'Small-batch coffee near Pike Place. Auburn family roasting with War Eagle pride in coffee capital.', 'Samantha Lee', 'hello@pugetsoundeaglecoffee.com', '(206) 555-0811', 'active', 'paid', 47.6097, -122.3425),
-- West Virginia
('Mountain State Tiger Electric', 'Home Services', '500 Virginia St E, Charleston, WV 25301', 'Charleston, WV', 'WV', 'https://mountainstatetigerelectric.com', 'Licensed electrician in Charleston. Auburn building construction grad wiring West Virginia homes.', 'Ryan Cooper', 'ryan@mountainstatetigerelectric.com', '(304) 555-0922', 'active', 'paid', 38.3498, -81.6326),
('Appalachian Eagle Dental', 'Healthcare', '100 Capitol St, Charleston, WV 25301', 'Charleston, WV', 'WV', 'https://appalachianeagledental.com', 'Gentle family dentistry in the Mountain State. Auburn dental grad serving West Virginia families.', 'Dr. Emily Turner', 'smile@appalachianeagledental.com', '(304) 555-0133', 'active', 'paid', 38.3498, -81.6329),
-- Wisconsin
('Badger Tiger Brewing', 'Food & Beverage', '235 N Water St, Milwaukee, WI 53202', 'Milwaukee, WI', 'WI', 'https://badgertigerbrewing.com', 'Craft beer in Brew City. Auburn grads bringing Southern brewing tradition to Wisconsin.', 'Chris Baker', 'cheers@badgertigerbrewing.com', '(414) 555-0244', 'active', 'paid', 43.0389, -87.9065),
('Dairy Eagle Financial', 'Financial Services', '780 N Water St, Milwaukee, WI 53202', 'Milwaukee, WI', 'WI', 'https://dairyeaglefinancial.com', 'Wealth management in Milwaukee. Auburn finance grad building long-term plans for Wisconsin families.', 'Jennifer Bauer', 'jennifer@dairyeaglefinancial.com', '(414) 555-0355', 'active', 'paid', 43.0450, -87.9096),
-- Wyoming
('Cowboy Tiger Construction', 'Construction', '109 E 2nd St, Casper, WY 82601', 'Casper, WY', 'WY', 'https://cowboytigerconstruction.com', 'Custom building in Wyoming. Auburn building science grad crafting homes that stand up to the wind.', 'Matt Henderson', 'matt@cowboytigerconstruction.com', '(307) 555-0466', 'active', 'paid', 42.8501, -106.3252),
('Yellowstone Eagle Realty', 'Real Estate', '200 W 1st St, Cheyenne, WY 82001', 'Cheyenne, WY', 'WY', 'https://yellowstoneeaglerealty.com', 'Wyoming real estate for Auburn families. Big sky living with Auburn values.', 'Susan Miller', 'susan@yellowstoneeaglerealty.com', '(307) 555-0577', 'active', 'paid', 41.1400, -104.8202);
